#该配置文件为自动文件，consul.yaml中的内容为配置中心中的配置文件内容
#如果不想在配置中心读取配置文件，需要将两份文件合成一份application.yaml
spring:
  config:
    import: "optional:consul:"
  application:
    name: springboot-cloud-stream-grpc-kafka
  cloud:
    consul:
      config:
        watch:
          enabled: true
        format: YAML
        prefixes:
        - config
        data-key: application
      discovery:
        tags:
        - grpcport=${grpc.server.port}
        register: true
        deregister: true
        enabled: true
        prefer-ip-address: true
        instance-id: spring/${spring.cloud.client.ip-address}:${grpc.server.port}
      host: 172.20.154.162
      port: 8500
