// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newGreeter.proto

package com.ipman.rpc.grpc.springboot.lib;

public final class NewGreeterOuterClass {
  private NewGreeterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NewHelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewHelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    int getRequestDataCount();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    boolean containsRequestData(
        java.lang.String key);
    /**
     * Use {@link #getRequestDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getRequestData();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getRequestDataMap();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */

    com.google.protobuf.Any getRequestDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */

    com.google.protobuf.Any getRequestDataOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code NewHelloRequest}
   */
  public static final class NewHelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NewHelloRequest)
      NewHelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NewHelloRequest.newBuilder() to construct.
    private NewHelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewHelloRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NewHelloRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NewHelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                requestData_ = com.google.protobuf.MapField.newMapField(
                    RequestDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
              requestData__ = input.readMessage(
                  RequestDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              requestData_.getMutableMap().put(
                  requestData__.getKey(), requestData__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetRequestData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.class, com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.Builder.class);
    }

    public static final int REQUEST_DATA_FIELD_NUMBER = 1;
    private static final class RequestDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                  com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_RequestDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> requestData_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetRequestData() {
      if (requestData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RequestDataDefaultEntryHolder.defaultEntry);
      }
      return requestData_;
    }

    public int getRequestDataCount() {
      return internalGetRequestData().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */

    @java.lang.Override
    public boolean containsRequestData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRequestData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRequestDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getRequestData() {
      return getRequestDataMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getRequestDataMap() {
      return internalGetRequestData().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getRequestDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetRequestData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getRequestDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetRequestData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetRequestData(),
          RequestDataDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
           : internalGetRequestData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
        requestData__ = RequestDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, requestData__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest)) {
        return super.equals(obj);
      }
      com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest other = (com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest) obj;

      if (!internalGetRequestData().equals(
          other.internalGetRequestData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetRequestData().getMap().isEmpty()) {
        hash = (37 * hash) + REQUEST_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRequestData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code NewHelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewHelloRequest)
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetRequestData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableRequestData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.class, com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.Builder.class);
      }

      // Construct using com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableRequestData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloRequest_descriptor;
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest getDefaultInstanceForType() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest build() {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest buildPartial() {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest result = new com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest(this);
        int from_bitField0_ = bitField0_;
        result.requestData_ = internalGetRequestData();
        result.requestData_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest) {
          return mergeFrom((com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest other) {
        if (other == com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest.getDefaultInstance()) return this;
        internalGetMutableRequestData().mergeFrom(
            other.internalGetRequestData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Any> requestData_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetRequestData() {
        if (requestData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RequestDataDefaultEntryHolder.defaultEntry);
        }
        return requestData_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetMutableRequestData() {
        onChanged();;
        if (requestData_ == null) {
          requestData_ = com.google.protobuf.MapField.newMapField(
              RequestDataDefaultEntryHolder.defaultEntry);
        }
        if (!requestData_.isMutable()) {
          requestData_ = requestData_.copy();
        }
        return requestData_;
      }

      public int getRequestDataCount() {
        return internalGetRequestData().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */

      @java.lang.Override
      public boolean containsRequestData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetRequestData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRequestDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getRequestData() {
        return getRequestDataMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Any> getRequestDataMap() {
        return internalGetRequestData().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getRequestDataOrDefault(
          java.lang.String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetRequestData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getRequestDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetRequestData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearRequestData() {
        internalGetMutableRequestData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */

      public Builder removeRequestData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRequestData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any>
      getMutableRequestData() {
        return internalGetMutableRequestData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */
      public Builder putRequestData(
          java.lang.String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRequestData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; request_data = 1;</code>
       */

      public Builder putAllRequestData(
          java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
        internalGetMutableRequestData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NewHelloRequest)
    }

    // @@protoc_insertion_point(class_scope:NewHelloRequest)
    private static final com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest();
    }

    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewHelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<NewHelloRequest>() {
      @java.lang.Override
      public NewHelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewHelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewHelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewHelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewHelloReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NewHelloReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    int getResponseDataCount();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    boolean containsResponseData(
        java.lang.String key);
    /**
     * Use {@link #getResponseDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getResponseData();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getResponseDataMap();
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */

    com.google.protobuf.Any getResponseDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */

    com.google.protobuf.Any getResponseDataOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code NewHelloReply}
   */
  public static final class NewHelloReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NewHelloReply)
      NewHelloReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NewHelloReply.newBuilder() to construct.
    private NewHelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewHelloReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NewHelloReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NewHelloReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                responseData_ = com.google.protobuf.MapField.newMapField(
                    ResponseDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
              responseData__ = input.readMessage(
                  ResponseDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              responseData_.getMutableMap().put(
                  responseData__.getKey(), responseData__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetResponseData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.class, com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.Builder.class);
    }

    public static final int RESPONSE_DATA_FIELD_NUMBER = 1;
    private static final class ResponseDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                  com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_ResponseDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> responseData_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetResponseData() {
      if (responseData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResponseDataDefaultEntryHolder.defaultEntry);
      }
      return responseData_;
    }

    public int getResponseDataCount() {
      return internalGetResponseData().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */

    @java.lang.Override
    public boolean containsResponseData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetResponseData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResponseDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getResponseData() {
      return getResponseDataMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getResponseDataMap() {
      return internalGetResponseData().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getResponseDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetResponseData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Any getResponseDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetResponseData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetResponseData(),
          ResponseDataDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
           : internalGetResponseData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
        responseData__ = ResponseDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, responseData__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply)) {
        return super.equals(obj);
      }
      com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply other = (com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply) obj;

      if (!internalGetResponseData().equals(
          other.internalGetResponseData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetResponseData().getMap().isEmpty()) {
        hash = (37 * hash) + RESPONSE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResponseData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing the greetings
     * </pre>
     *
     * Protobuf type {@code NewHelloReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NewHelloReply)
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetResponseData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableResponseData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.class, com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.Builder.class);
      }

      // Construct using com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableResponseData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.internal_static_NewHelloReply_descriptor;
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply getDefaultInstanceForType() {
        return com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply build() {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply buildPartial() {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply result = new com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply(this);
        int from_bitField0_ = bitField0_;
        result.responseData_ = internalGetResponseData();
        result.responseData_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply) {
          return mergeFrom((com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply other) {
        if (other == com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply.getDefaultInstance()) return this;
        internalGetMutableResponseData().mergeFrom(
            other.internalGetResponseData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Any> responseData_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetResponseData() {
        if (responseData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResponseDataDefaultEntryHolder.defaultEntry);
        }
        return responseData_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetMutableResponseData() {
        onChanged();;
        if (responseData_ == null) {
          responseData_ = com.google.protobuf.MapField.newMapField(
              ResponseDataDefaultEntryHolder.defaultEntry);
        }
        if (!responseData_.isMutable()) {
          responseData_ = responseData_.copy();
        }
        return responseData_;
      }

      public int getResponseDataCount() {
        return internalGetResponseData().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */

      @java.lang.Override
      public boolean containsResponseData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetResponseData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResponseDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getResponseData() {
        return getResponseDataMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Any> getResponseDataMap() {
        return internalGetResponseData().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getResponseDataOrDefault(
          java.lang.String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetResponseData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Any getResponseDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetResponseData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearResponseData() {
        internalGetMutableResponseData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */

      public Builder removeResponseData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableResponseData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any>
      getMutableResponseData() {
        return internalGetMutableResponseData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */
      public Builder putResponseData(
          java.lang.String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableResponseData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; response_data = 1;</code>
       */

      public Builder putAllResponseData(
          java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
        internalGetMutableResponseData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NewHelloReply)
    }

    // @@protoc_insertion_point(class_scope:NewHelloReply)
    private static final com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply();
    }

    public static com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewHelloReply>
        PARSER = new com.google.protobuf.AbstractParser<NewHelloReply>() {
      @java.lang.Override
      public NewHelloReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewHelloReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewHelloReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewHelloReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ipman.rpc.grpc.springboot.lib.NewGreeterOuterClass.NewHelloReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewHelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewHelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewHelloRequest_RequestDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewHelloRequest_RequestDataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewHelloReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewHelloReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewHelloReply_ResponseDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewHelloReply_ResponseDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020newGreeter.proto\032\031google/protobuf/any." +
      "proto\"\224\001\n\017NewHelloRequest\0227\n\014request_dat" +
      "a\030\001 \003(\0132!.NewHelloRequest.RequestDataEnt" +
      "ry\032H\n\020RequestDataEntry\022\013\n\003key\030\001 \001(\t\022#\n\005v" +
      "alue\030\002 \001(\0132\024.google.protobuf.Any:\0028\001\"\223\001\n" +
      "\rNewHelloReply\0227\n\rresponse_data\030\001 \003(\0132 ." +
      "NewHelloReply.ResponseDataEntry\032I\n\021Respo" +
      "nseDataEntry\022\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\013" +
      "2\024.google.protobuf.Any:\0028\0012<\n\nNewGreeter" +
      "\022.\n\010SayHello\022\020.NewHelloRequest\032\016.NewHell" +
      "oReply\"\000B#\n!com.ipman.rpc.grpc.springboo" +
      "t.libb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_NewHelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewHelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewHelloRequest_descriptor,
        new java.lang.String[] { "RequestData", });
    internal_static_NewHelloRequest_RequestDataEntry_descriptor =
      internal_static_NewHelloRequest_descriptor.getNestedTypes().get(0);
    internal_static_NewHelloRequest_RequestDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewHelloRequest_RequestDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_NewHelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NewHelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewHelloReply_descriptor,
        new java.lang.String[] { "ResponseData", });
    internal_static_NewHelloReply_ResponseDataEntry_descriptor =
      internal_static_NewHelloReply_descriptor.getNestedTypes().get(0);
    internal_static_NewHelloReply_ResponseDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewHelloReply_ResponseDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
